name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    name: Publish Docker
    on: [push]
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: phantam/cnmaestro-report
            username: ${{ secrets.GITHUBUSERNAME }}
            password: ${{ secrets.GITHUBACCESSTOKEN }}
